Document: irtk
Title: Debian irtk Manual
Author: <insert document author here>
Abstract: This manual describes what irtk is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/irtk/irtk.sgml.gz

Format: postscript
Files: /usr/share/doc/irtk/irtk.ps.gz

Format: text
Files: /usr/share/doc/irtk/irtk.text.gz

Format: HTML
Index: /usr/share/doc/irtk/html/index.html
Files: /usr/share/doc/irtk/html/*.html
